#!/usr/bin/env bash
# Script that Installs haproxy and Configure HAproxy so that it send traffic to two servers

CONF="\
frontend my_fronted
bind *:80
mode http
default_backend my_backend

backend my_backend
balance roundrobin
server 352137-web-01 34.234.193.57:80 check
server 352137-web-02 52.204.102.173:80 check
"
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo echo "$CONF" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
