#!/usr/bin/env bash
# Installs and setup firewall: ufw

sudo apt-get -y install ufw
sudo ufw status
sudo ufw enable -y
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow ssh
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp